/**
 * ResponsesDueCard — surfaces when the responses-due deadline has passed
 * with incomplete responses. Per the spec this is a *dedicated* decision
 * surface, not a generic toast.
 *
 * Shows three actions:
 *   1. Lock without holdouts — scrolls to / surfaces the decision queue
 *      (recommendations are auto-generated by the scheduler at this point).
 *   2. Send one more nudge — fires the next scheduled nudge for any
 *      remaining holdout participant.
 *   3. Extend deadline — opens a single-date picker, updates the trip's
 *      responses_due_date, which retriggers the cadence on the next tick.
 *
 * Hidden when responses_due hasn't passed yet OR every participant has
 * responded.
 */
import React, { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SingleDatePicker } from '@/components/SingleDatePicker';
import { useUpdateTrip, useTrip } from '@/hooks/useTrips';
import { useSessionParticipants, useSendNudgeNow } from '@/hooks/useTripSession';
import { useRespondents } from '@/hooks/useRespondents';
import { daysUntil, formatCadenceDate } from '@/lib/cadence';
import { normalizePhone } from '@/lib/phone';

interface Props {
  tripId: string;
  sessionId: string | undefined;
  /** Optional callback so the parent can scroll to the decision queue card. */
  onJumpToDecisions?: () => void;
}

export function ResponsesDueCard({ tripId, sessionId, onJumpToDecisions }: Props) {
  const { data: trip } = useTrip(tripId);
  const { data: participants = [] } = useSessionParticipants(sessionId);
  const { data: respondents = [] } = useRespondents(tripId);
  const updateTrip = useUpdateTrip();
  const sendNudge = useSendNudgeNow(sessionId);

  const [extendOpen, setExtendOpen] = useState(false);

  // Did anyone respond? Match by normalized phone.
  const respondedPhones = useMemo(() => {
    const set = new Set<string>();
    for (const r of respondents) {
      if (!r.rsvp && !r.preferences) continue;
      const norm = normalizePhone(r.phone ?? '');
      if (norm) set.add(norm);
    }
    return set;
  }, [respondents]);

  const holdouts = useMemo(() => {
    return participants.filter((p) => {
      if (p.status !== 'active' || !p.is_attending || p.is_planner) return false;
      const norm = normalizePhone(p.phone) ?? '';
      return !respondedPhones.has(norm);
    });
  }, [participants, respondedPhones]);

  const responsesDueDays = daysUntil(trip?.responses_due_date ?? null);
  const isPastDue = responsesDueDays !== null && responsesDueDays <= 0;

  if (!trip || !isPastDue || holdouts.length === 0) return null;

  const overdueLabel =
    responsesDueDays === 0 ? 'today'
    : responsesDueDays === -1 ? 'yesterday'
    : `${Math.abs(responsesDueDays)} days ago`;

  function handleSendNudge() {
    Alert.alert(
      'Send one more nudge?',
      `Rally will send the next scheduled nudge to ${holdouts.length} ${holdouts.length === 1 ? 'person' : 'people'} who haven't responded.`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Send',
          onPress: async () => {
            // Fire one nudge per holdout. Best-effort.
            const results = await Promise.all(
              holdouts.map((h) => sendNudge.mutateAsync(h.id)),
            );
            const fired = results.filter((r) => r.ok).length;
            Alert.alert(
              'Nudges queued',
              `Rally will send ${fired} of ${holdouts.length} nudges in the next 15 minutes.`,
            );
          },
        },
      ],
    );
  }

  function handleExtend(newDate: string | null) {
    if (!newDate) return;
    updateTrip.mutate(
      { id: tripId, responses_due_date: newDate },
      {
        onError: () => Alert.alert('Could not extend', 'Try again.'),
      },
    );
  }

  function handleLockNow() {
    if (onJumpToDecisions) {
      onJumpToDecisions();
      return;
    }
    Alert.alert(
      'Lock decisions now',
      'Scroll up to the Pending Decisions card to approve each one. Holdouts will get a tailored SMS once you lock.',
    );
  }

  return (
    <>
      <SingleDatePicker
        visible={extendOpen}
        value={trip.responses_due_date}
        onConfirm={handleExtend}
        onClose={() => setExtendOpen(false)}
        title="Extend response deadline"
        confirmLabel="Extend deadline"
        minDate={new Date().toISOString().slice(0, 10)}
      />

      <View style={styles.card}>
        <View style={styles.headerRow}>
          <Ionicons name="alarm" size={18} color="#9A2A2A" />
          <Text style={styles.title}>Responses were due {overdueLabel}</Text>
        </View>

        <Text style={styles.body}>
          {holdouts.length} {holdouts.length === 1 ? 'person hasn\'t' : 'people haven\'t'} responded yet
          {trip.book_by_date ? ` · book-by ${formatCadenceDate(trip.book_by_date)}` : ''}
        </Text>

        <View style={styles.holdoutChips}>
          {holdouts.slice(0, 6).map((h) => (
            <View key={h.id} style={styles.chip}>
              <Text style={styles.chipText} numberOfLines={1}>
                {h.display_name ?? h.phone}
              </Text>
            </View>
          ))}
          {holdouts.length > 6 ? (
            <Text style={styles.chipMore}>+ {holdouts.length - 6} more</Text>
          ) : null}
        </View>

        <View style={styles.actions}>
          <Pressable onPress={handleLockNow} style={[styles.btn, styles.btnPrimary]} accessibilityRole="button">
            <Text style={styles.btnPrimaryText}>Lock without holdouts</Text>
          </Pressable>
          <Pressable onPress={handleSendNudge} style={[styles.btn, styles.btnSecondary]} accessibilityRole="button">
            <Text style={styles.btnSecondaryText}>Send one more nudge</Text>
          </Pressable>
          <Pressable onPress={() => setExtendOpen(true)} style={[styles.btn, styles.btnSecondary]} accessibilityRole="button">
            <Text style={styles.btnSecondaryText}>Extend deadline</Text>
          </Pressable>
        </View>
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: '#FEF1EF',
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#F4C7BD',
    padding: 14,
    marginBottom: 18,
    gap: 10,
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  title: { fontSize: 14, fontWeight: '700', color: '#9A2A2A' },
  body: { fontSize: 13, color: '#404040', lineHeight: 18 },

  holdoutChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignItems: 'center' },
  chip: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F4C7BD',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    maxWidth: 140,
  },
  chipText: { fontSize: 12, color: '#9A2A2A', fontWeight: '600' },
  chipMore: { fontSize: 12, color: '#888' },

  actions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  btn: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
  },
  btnPrimary: { backgroundColor: '#9A2A2A' },
  btnPrimaryText: { fontSize: 13, fontWeight: '700', color: 'white' },
  btnSecondary: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#F4C7BD' },
  btnSecondaryText: { fontSize: 13, fontWeight: '600', color: '#9A2A2A' },
});
